name: Pervaziv AI Code Review-2

on:
  push:
    branches:
      - main

jobs:
  pervaziv-ai-action:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: write
      pull-requests: write

    steps:
      - uses: jyothsnalade/cortex-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          console-url: https://console.pervaziv.com
